######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 20 18:38:20 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qt_1.cpp
