######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 20 18:45:51 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qt_1.cpp
