######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 20 20:31:48 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += app_4.cpp
