######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 20 20:08:50 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += qt_2.cpp
