######################################################################
# Automatically generated by qmake (2.01a) Sat Aug 20 22:01:49 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += finddialog.h
SOURCES += finddialog.cpp main.cpp
